In [2]:
from sklearn.impute import SimpleImputer
import pandas as pd
data=pd.read_csv("./day08_Narrativedata.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  891 non-null    int64  
 1   Age         714 non-null    float64
 2   Sex         891 non-null    object 
 3   Embarked    889 non-null    object 
 4   Survived    891 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 34.9+ KB


In [12]:
import numpy as np
Age=data.loc[:,"Age"].values
Age=Age[:,np.newaxis]
Age.shape
Age

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [  nan],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [  nan],
       [31.  ],
       [  nan],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [  nan],
       [19.  ],
       [  nan],
       [  nan],
       [40.  ],
       [  nan],
       [  nan],
       [66.  ],
       [28.  ],
       [42.  ],
       [  nan],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [  nan],
       [ 3.  ],
       [19.  ],
       [  nan],
       [  nan],
       [  nan],
       [  nan],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [  nan],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [13]:
#用0进行填充
impu_0=SimpleImputer(missing_values=np.nan,strategy="constant",fill_value=0)
#用均值进行填充
impu_mean=SimpleImputer(missing_values=np.nan,strategy="mean")
#用中位数填充
impu_median=SimpleImputer(missing_values=np.nan,strategy="median")
impu_0=impu_0.fit_transform(Age)
impu_mean=impu_mean.fit_transform(Age)
impu_median=impu_median.fit_transform(Age)

In [14]:
impu_0

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [ 0.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [ 0.  ],
       [31.  ],
       [ 0.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [ 0.  ],
       [19.  ],
       [ 0.  ],
       [ 0.  ],
       [40.  ],
       [ 0.  ],
       [ 0.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [ 0.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [ 0.  ],
       [ 3.  ],
       [19.  ],
       [ 0.  ],
       [ 0.  ],
       [ 0.  ],
       [ 0.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [ 0.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [15]:
impu_mean

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765],
       [35.        ],
       [34.        ],
       [15.        ],
       [28.        ],
       [ 8.        ],
       [38.        ],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.69911765],
       [29.69911765],
       [66.        ],
       [28.        ],
       [42.        ],
       [29.69911765],
       [21.        ],
       [18.        ],
       [14.        ],
       [40.        ],
       [27.        ],
       [29.69911765],
       [ 3.        ],
       [19.        ],
       [29

In [16]:
impu_median

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [28.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [28.  ],
       [31.  ],
       [28.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [28.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [40.  ],
       [28.  ],
       [28.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [28.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [28.  ],
       [ 3.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [28.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [18]:
impu_median=SimpleImputer(missing_values=np.nan,strategy="median")
data.loc[:,"Age"]=impu_median.fit_transform(Age)

In [19]:
data.loc[:,"Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  891 non-null    int64  
 1   Age         891 non-null    float64
 2   Sex         891 non-null    object 
 3   Embarked    889 non-null    object 
 4   Survived    891 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 34.9+ KB


In [21]:
data.head()

Unnamed: 0   Age     Sex Embarked Survived
0           0  22.0    male        S       No
1           1  38.0  female        C      Yes
2           2  26.0  female        S      Yes
3           3  35.0  female        S      Yes
4           4  35.0    male        S       No

In [22]:
# strategy中表示的是用那个众数进行填充，可以用于非数值型的数据
impu_most_frequent=SimpleImputer(missing_values=np.nan
                                  ,strategy="most_frequent")

Embarked=data.loc[:,"Embarked"].values.reshape(-1,1)
data.loc[:,"Embarked"]=impu_most_frequent.fit_transform(Embarked)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  891 non-null    int64  
 1   Age         891 non-null    float64
 2   Sex         891 non-null    object 
 3   Embarked    891 non-null    object 
 4   Survived    891 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 34.9+ KB
